---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package & php support for apch
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
